/* 
 * 运营商业务API接口
 *
 * 运营商业务API接口平台应用程序接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: henryxm@163.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using Org.OpenAPITools.Client;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing OperatorApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class OperatorApiTests
    {
        private OperatorApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new OperatorApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of OperatorApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOf' OperatorApi
            //Assert.IsInstanceOf(typeof(OperatorApi), instance);
        }

        
        /// <summary>
        /// Test Demoback
        /// </summary>
        [Test]
        public void DemobackTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //CallbackData data = null;
            //var response = instance.Demoback(data);
            //Assert.IsInstanceOf(typeof(string), response, "response is string");
        }
        
        /// <summary>
        /// Test Request
        /// </summary>
        [Test]
        public void RequestTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //CodeRequest request = null;
            //var response = instance.Request(request);
            //Assert.IsInstanceOf(typeof(OutResponseOfCodeResponse), response, "response is OutResponseOfCodeResponse");
        }
        
        /// <summary>
        /// Test Verify
        /// </summary>
        [Test]
        public void VerifyTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //CodeVerify verify = null;
            //var response = instance.Verify(verify);
            //Assert.IsInstanceOf(typeof(OutResponseOfCodeResponse), response, "response is OutResponseOfCodeResponse");
        }
        
    }

}
