/* 
 * 运营商业务API接口
 *
 * 运营商业务API接口平台应用程序接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: henryxm@163.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing Balance
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class BalanceTests
    {
        // TODO uncomment below to declare an instance variable for Balance
        //private Balance instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Balance
            //instance = new Balance();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Balance
        /// </summary>
        [Test]
        public void BalanceInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" Balance
            //Assert.IsInstanceOf(typeof(Balance), instance);
        }


        /// <summary>
        /// Test the property '_Balance'
        /// </summary>
        [Test]
        public void _BalanceTest()
        {
            // TODO unit test for the property '_Balance'
        }
        /// <summary>
        /// Test the property 'Reward'
        /// </summary>
        [Test]
        public void RewardTest()
        {
            // TODO unit test for the property 'Reward'
        }
        /// <summary>
        /// Test the property 'Total'
        /// </summary>
        [Test]
        public void TotalTest()
        {
            // TODO unit test for the property 'Total'
        }
        /// <summary>
        /// Test the property 'UserUuid'
        /// </summary>
        [Test]
        public void UserUuidTest()
        {
            // TODO unit test for the property 'UserUuid'
        }
        /// <summary>
        /// Test the property 'Voucher'
        /// </summary>
        [Test]
        public void VoucherTest()
        {
            // TODO unit test for the property 'Voucher'
        }

    }

}
