/* 
 * 运营商业务API接口
 *
 * 运营商业务API接口平台应用程序接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: henryxm@163.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing CodeRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CodeRequestTests
    {
        // TODO uncomment below to declare an instance variable for CodeRequest
        //private CodeRequest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CodeRequest
            //instance = new CodeRequest();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CodeRequest
        /// </summary>
        [Test]
        public void CodeRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" CodeRequest
            //Assert.IsInstanceOf(typeof(CodeRequest), instance);
        }


        /// <summary>
        /// Test the property 'AppName'
        /// </summary>
        [Test]
        public void AppNameTest()
        {
            // TODO unit test for the property 'AppName'
        }
        /// <summary>
        /// Test the property 'AppPackage'
        /// </summary>
        [Test]
        public void AppPackageTest()
        {
            // TODO unit test for the property 'AppPackage'
        }
        /// <summary>
        /// Test the property 'Channel'
        /// </summary>
        [Test]
        public void ChannelTest()
        {
            // TODO unit test for the property 'Channel'
        }
        /// <summary>
        /// Test the property 'Ip'
        /// </summary>
        [Test]
        public void IpTest()
        {
            // TODO unit test for the property 'Ip'
        }
        /// <summary>
        /// Test the property 'Mobile'
        /// </summary>
        [Test]
        public void MobileTest()
        {
            // TODO unit test for the property 'Mobile'
        }
        /// <summary>
        /// Test the property 'Param'
        /// </summary>
        [Test]
        public void ParamTest()
        {
            // TODO unit test for the property 'Param'
        }
        /// <summary>
        /// Test the property 'Product'
        /// </summary>
        [Test]
        public void ProductTest()
        {
            // TODO unit test for the property 'Product'
        }
        /// <summary>
        /// Test the property 'Ua'
        /// </summary>
        [Test]
        public void UaTest()
        {
            // TODO unit test for the property 'Ua'
        }

    }

}
