/* 
 * 运营商业务API接口
 *
 * 运营商业务API接口平台应用程序接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: henryxm@163.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing OutResponseOfCodeResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class OutResponseOfCodeResponseTests
    {
        // TODO uncomment below to declare an instance variable for OutResponseOfCodeResponse
        //private OutResponseOfCodeResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of OutResponseOfCodeResponse
            //instance = new OutResponseOfCodeResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of OutResponseOfCodeResponse
        /// </summary>
        [Test]
        public void OutResponseOfCodeResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" OutResponseOfCodeResponse
            //Assert.IsInstanceOf(typeof(OutResponseOfCodeResponse), instance);
        }


        /// <summary>
        /// Test the property 'Code'
        /// </summary>
        [Test]
        public void CodeTest()
        {
            // TODO unit test for the property 'Code'
        }
        /// <summary>
        /// Test the property 'Data'
        /// </summary>
        [Test]
        public void DataTest()
        {
            // TODO unit test for the property 'Data'
        }
        /// <summary>
        /// Test the property 'Msg'
        /// </summary>
        [Test]
        public void MsgTest()
        {
            // TODO unit test for the property 'Msg'
        }

    }

}
